name: Build-RPM

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: enstoredev/enstore-build:latest
    steps:
    - uses: actions/checkout@v2
    - name: build enstore rpm
      run: |
       mkdir -p ~/rpmbuild/SOURCES ~/rpmbuild/SPECS
       tar czvf enstore.tgz . --exclude enstore.tgz --exclude-vcs
       cd ~/rpmbuild/
       cp ~/enstore/enstore.tgz SOURCES/
       cp ~/enstore/spec/enstore_RH7_python_2.7.16_with_start_on_boot.spec SPECS/
       rpmbuild -ba SPECS/enstore_RH7_python_2.7.16_with_start_on_boot.spec > 6.3.4-15.out 2>&1
       cat 6.3.4-15.out
    - name: upload enstore rpm as artifact
      uses: actions/upload-artifact@v2
      with: 
        name: enstore-rpm
        path: ~/rpmbuild/RPMS/x86_64/enstore-*.rpm
