name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
       find . -name '*.py' > ./python_file_list
       export num_files=$(wc -l ./python_file_list)
       export opts=' --disable=all --enable=syntax-error'
       export opts=$opts' --enable=bad-thread-instantiation'
       export opts=$opts' --enable=used-before-assignment'
       export opts=$opts'--enable=undefined-variable --score no'
       echo "found $num_files python files to analyze"
       for P in $(cat ./python_file_list) ; do  pylint $opts $P 2>/dev/null || echo $(echo pylint $P exited code $?)   ; done
       echo "analyzed $num_files python files with pylint"
