name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
       export opts=" --disable=all --enable=syntax-error --enable=bad-thread-instantiation --enable=used-before-assignment --enable=undefined-variable --score no "
       for P in $(find .  -name '*.py') ; do  pylint $opts $P 2>/dev/null || echo pylint $P exited code $?   ; done
